name: flutter_inbrain
description: Inbrain surveys for Android & iOS
version: 1.2.0
homepage: https://github.com/AnavrinApps/flutter_plugins 

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.anavrinapps.flutter_inbrain
        pluginClass: FlutterInbrainPlugin
      ios:
        pluginClass: FlutterInbrainPlugin